name: Vigilnz Scan
on: 
  push: # runs on every push 
  workflow_dispatch: # lets you run manually from the Actions tab

jobs:
  Vigilnz_Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Vigilnz Scan
        uses: vigilnz/vigilnz-scan-action@master
        with: 
          vigilnzApiKey: ${{ secrets.VIGILNZ_API_KEY }}
          scanTypes: "CONTAINER SCAN"
          containerImage: "myorg/myapp:1.0.0"
          containerProvider: "dockerhub"
          containerAuthType: "username-password"
          containerUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          containerPassword: ${{ secrets.DOCKERHUB_PASSWORD }}
  
  Vigilnz_Scan1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Vigilnz Scan
        uses: vigilnz/vigilnz-scan-action@master
        with: 
          vigilnzApiKey: ${{ secrets.VIGILNZ_API_KEY }}
          scanTypes: "CONTAINER SCAN"
          containerImage: "myapp:latest"
          containerProvider: "aws-ecr"
          containerRegistryType: "ecr-private"
          containerRegistryUrl: "123456789012.dkr.ecr.us-east-1.amazonaws.com"
          containerAuthType: "token"
          containerToken: "asdasdasd"
        
